#
# THIS MAKEFILE WORKS WITH MICROSOFT NMAKE ONLY
#

BASENAME = volformat

RESOURCES = $(BASENAME).res

all: $(BASENAME).exe

OBJECTS = $(BASENAME).obj volumes1.obj combo.obj crc.obj \
        crypto.obj dlgcode.obj endian.obj fat.obj random.obj \
        uncroot.obj format.obj pkcs5.obj password.obj progress.obj \
	testcrypt.obj redtick.obj cmdline.obj

CFLAGS = $(CFLAGS_G) /DVOLFORMAT /YXe4mdefs.h

!include ..\common.ms

$(BASENAME).res : $(BASENAME).rc ../common/dlgs.rc

$(BASENAME).exe : $(OBJECTS) $(RESOURCES)   crypto.lib 
	$(LINK_G) $(OBJECTS) $(RESOURCES) crypto.lib /subsystem:windows

